> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Title Here

An short introduction about PyTorch and about the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.dstack

Add some explanations

In [4]:
# Example 1 - working (change this)
t1 = torch.tensor([3, 4])
t2 = torch.tensor([2, 5])
torch.dstack((t1,t2))

tensor([[[3, 2],
         [4, 5]]])

Explanation about example

In [5]:
# Example 2 - working
t1 = torch.tensor([3, 4, 5])
t2 = torch.tensor([2, 5, 1])
torch.dstack((t1,t2))

tensor([[[3, 2],
         [4, 5],
         [5, 1]]])

Explanation about example

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.tensor([3, 4])
t2 = torch.tensor([2, 5, 1])
torch.dstack((t1,t2))

RuntimeError: ignored

Explanation about example:

Index error can occur because of given dimensions of the torch arrays. They must have same dimension.

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 2 - ???

Add some explanations

In [7]:
# Example 1 - working
torch.arange(5)

tensor([0, 1, 2, 3, 4])

Explanation about example

In [11]:
# Example 2 - working
torch.arange(0, 50, 10)

tensor([ 0, 10, 20, 30, 40])

Explanation about example

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(50, 0, 5)

RuntimeError: ignored

Explanation about example:

An error was occured because it could not be counted by adding 5 from 50 to 0.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 3 - ???

Add some explanations

In [14]:
# Example 1 - working
t1 = torch.tensor([3, 4, 5, 6])
torch.reshape(t1, (2,2))

tensor([[3, 4],
        [5, 6]])

Explanation about example

In [15]:
# Example 2 - working
t1 = torch.tensor([2, 3, 4, 5, 6, 7])
torch.reshape(t1, (2,3))

tensor([[2, 3, 4],
        [5, 6, 7]])

Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.tensor([2, 3, 4, 5, 6, 7])
torch.reshape(t1, (2,2))

RuntimeError: ignored

Explanation about example

The shape of a torch array can not be reshaped to (2,2). Input size mush have related to desired size.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - ???

Add some explanations

In [19]:
# Example 1 - working
t1 = torch.tensor([1., 2., 3., 4., 5., 6.]) # Let's create a randon Tensor size (8,8,8)

torch.std_mean(t1)

(tensor(1.8708), tensor(3.5000))

Explanation about example

In [21]:
# Example 2 - working
t1 = torch.rand(2,2) # Let's create a randon Tensor size (8,8,8)

torch.std_mean(t1)

(tensor(0.2009), tensor(0.5430))

Explanation about example

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.rand(2,2) # Let's create a randon Tensor size (8,8,8)

torch.std_mean(t1, 2)

IndexError: ignored

Explanation about example

Error was occured because the dimension of range is lower than desired.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - ???

Add some explanations

In [25]:
# Example 1 - working
t1 = torch.tensor([5, 10])
t2 = torch.tensor([3, 6])
torch.hstack((t1, t2))

tensor([ 5, 10,  3,  6])

Explanation about example

In [28]:
# Example 2 - working
t1 = torch.tensor([[5, 10],[2, 4]])
t2 = torch.tensor([[3, 6],[4, 8]])
torch.hstack((t1, t2))

tensor([[ 5, 10,  3,  6],
        [ 2,  4,  4,  8]])

Explanation about example

In [30]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.tensor([5, 10, 15])
t2 = torch.tensor([[3, 6],[4, 8]])
torch.hstack((t1, t2))

RuntimeError: ignored

Explanation about example

Tensor arrays must have same number of dimension.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
